version: '3.7'
networks:
  default:
    driver: overlay
    attachable: true
    external: false
  proxy:
    external: true
services:
  cert-manager:
    image: satishweb/docker-flow-proxy-cert-manager-letsencrypt-aws-route53:latest
    hostname: cert-manager
    init: true
    networks:
      - proxy
    environment:
      # DOMAIN_<SEQUENCE>: Multiple values can be given with comma separation.
      #                    All values must be a subdomain of same base domain. e.g. sub1.satishweb.com,sub2.satishweb.com
      #                    Each value must be a FQDN. e.g. subdomain.satishweb.com
      #                    Avoid using variable that starts with DOMAIN_ for any other purpose than domain list
      DOMAIN_1: "dns.YOURDOMAIN.COM"
      DEBUG: "0"
      CERTBOT_EMAIL: webmaster@YOURDOMAIN.COM
      PROXY_ADDRESS: "proxy"
      PROXY_PORT: "8080"
      AWS_ACCESS_KEY_ID: ACCESSKEY
      AWS_SECRET_ACCESS_KEY: SECRETKEY
      AWS_REGION: us-east-1
      AWS_HOSTED_ZONE_ID: AWS_HOSTED_R53_ZONE_ID
      #CERTBOTMODE: "staging"
      # Comment above line to go in production mode
    volumes:
      - ../../data/certs/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 99
        window: 180s
      # resources:
      #   limits:
      #     cpus: '1.00'
      #     memory: 1024M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 512M
    labels:
      - "com.satishweb.description=Certificate Manager"
