version: '3.7'
networks:
  default:
    driver: overlay
    attachable: true
    external: false
  proxy:
    external: true
services:
  proxy:
    image: dockerflow/docker-flow-proxy:latest
    hostname: proxy
    init: true
    networks:
      - default
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../data/proxy/certs:/certs
    environment:
      TINI_SUBREAPER: 1
      LISTENER_ADDRESS: swarm-listener
      MODE: swarm
      COMPRESSION_ALGO: gzip
      COMPRESSION_TYPE: text/css text/html text/javascript application/javascript text/plain text/xml application/json
      CONNECTION_MODE: http-keep-alive
      DEBUG: "true"
      HTTPS_ONLY: "true"
      STATS_URI: /stats
      # Lets add extra frontend code to add trailing slash if virtual directory is accessed without trailing slash
      EXTRA_FRONTEND: http-request set-log-level debug,http-response set-log-level debug,capture request header User-Agent len 64,acl is_vd path -i /dns-admin,http-request redirect scheme https drop-query append-slash if is_vd,http-response set-header X-Frame-Options DENY,http-response set-header X-Content-Type-Options nosniff,
      EXTRA_GLOBAL:
      SSL_BIND_OPTIONS: no-sslv3 no-tls-tickets no-tlsv10 no-tlsv11
      SSL_BIND_CIPHERS: EECDH+AESGCM:EDH+AESGCM
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.labels.type == worker
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 99
        window: 180s
      # resources:
      #   limits:
      #     cpus: '1.00'
      #     memory: 1024M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 512M
    healthcheck:
      test: [ "CMD", "sh", "-c", "/usr/local/bin/check.sh"]
      interval: 2m
      timeout: 1m
      retries: 3
    labels:
      - "com.satishweb.description=HA Proxy Server"
