version: '3.7'
networks:
  default:
    driver: overlay
    attachable: true
    external: false
  proxy:
    external: true
services:
  unbound:
    image: satishweb/unbound:latest
    hostname: unbound
    init: true
    networks:
      - default
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./unbound.sample.conf:/templates/unbound.sample.conf
      - ../../data/unbound/custom.hosts:/etc/unbound/custom.hosts
    environment:
      DEBUG: "0"
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.labels.type == worker
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 99
        window: 180s
      # resources:
      #   limits:
      #     cpus: '1.00'
      #     memory: 1024M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 512M
    labels:
      - "com.satishweb.description=Unbound DNS Cache Service"
