version: '3.7'
networks:
  default:
    driver: overlay
    attachable: true
    external: false
  proxy:
    external: true
services:
  doh-server:
    image: satishweb/doh-server:latest
    hostname: doh-server
    init: true
    networks:
      - default
      - proxy
    environment:
      DEBUG: "0"
      UPSTREAM_DNS_SERVER: "udp:unbound:53"
      DOH_HTTP_PREFIX: "/getnsrecord"
      DOH_SERVER_LISTEN: ":8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "false"
    #volumes:
      # - ./doh-server.conf:/server/doh-server.conf
      # - ./app-config:/app-config
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.labels.type == worker
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 99
        window: 180s
      # resources:
      #   limits:
      #     cpus: '1.00'
      #     memory: 1024M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 512M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath='/getnsrecord'
        - com.df.port=8053
    depends_on:
      - unbound
    labels:
      - "com.satishweb.description=DNS Over HTTP Service"
